name: Continuous Deploy #action名称
on:  #在推送的时候运行此action
   push:
        branches: [site]

jobs:
  deploy_job:
    runs-on: ubuntu-latest  #运行环境
    name: build
    steps:
      # check out the repository
      - name: Checkout    
        uses: actions/checkout@v2    


      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0 
        with:  
          username: 'root'   #ssh user name
          server: '${{ secrets.SERVER_IP }}' 
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          local_path: './site/*' 
          remote_path: '/www/wwwroot/wiki.blicube.com/blikvm'
